
---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  labels:
    app: registry
spec:
  selector:
    app: registry
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http-port
  type: LoadBalancer
