openapi: 3.0.0
info:
  title: Developer API
  version: 1.0.0

paths:
  /developers:
    post:
      summary: Create a developer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Developer'
      responses:
        201:
          description: Developer created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Developer'
    get:
      summary: Get a list of developers
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Developer'

  /developers/{id}:
    put:
      summary: Update a developer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Developer'
      responses:
        200:
          description: Developer updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Developer'
        404:
          description: Developer not found

    delete:
      summary: Delete a developer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Developer deleted
        404:
          description: Developer not found

components:
  schemas:
    Developer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        company:
          type: string
        emailAddress:
          type: string
          format: email
        phoneNumber:
          type: string
          pattern: '^(\+\d{1,3}[- ]?)?\d{10}$'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
      required:
        - company
        - emailAddress
        - phoneNumber

    Contact:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        emailAddress:
          type: string
          format: email
        phone:
          type: string
          pattern: '^(\+\d{1,3}[- ]?)?\d{10}$'
        role:
          type: string
      required:
        - firstName
        - lastName
